### ISSUE TITLE
Split time error

### ISSUE THREAD

**Issue by larpSTATGL** [statisticssweden/PxWeb#201]
**Describe the bug**
Split Time cause fatal error

**To Reproduce**

Try:
https://pxwebdemo.scb.se/sq/1dfb37ed-6db8-4287-a673-5982af14fccc

select 
edit & calculate

split time variable

**Actual behavior**
An error has occurred. The error has been registered

**Expected behavior**
This also happens on https://bank.stat.gl - pxweb2021v1

It used to be good (2019v1)

:-) LarsP

**Comment by likp** [comment]
@statgreen could you attach the error message from the log. Would be very helpful when trying to recreate the error.

**Comment by statgreen** [comment]
Sorry - did not see your message til now. But it should be the same on your demo site

:-) LarsP

2021-12-10 08:13:04,100 [30] ERROR PXWeb.Modules.PXWebHttpModule - PX-Web Application Error ---> Offending URL: https://bank.stat.gl/pxweb/en/Greenland/Greenland__BE__BE85/BEXBBDK.px/table/tableViewLayout1/?rxid=BEXSTA10-12-2021+07:24:53 -- Source: System.Web -- Message: Exception of type 'System.Web.HttpUnhandledException' was thrown. -- Inner exception message: Object reference not set to an instance of an object. -- Stack trace:    at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
2021-12-10 08:13:04,100 [30] ERROR Global - System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PCAxis.Web.Controls.CommandBar.CommandBarCodebehind.HidePluginDropDown(DropDownList dropdown, String pluginId)
   at PCAxis.Web.Controls.CommandBar.CommandBarCodebehind.UpdatePluginVisibility(CommandBarPluginInfo plugin, String pluginCategory)
   at PCAxis.Web.Controls.CommandBar.CommandBarCodebehind.HandleOperation(CommandBarPluginInfo plugin, String pluginKey)
   at PCAxis.Web.Controls.CommandBar.CommandBarCodebehind.HandlePlugin(String pluginKey, Boolean shortcut)
   at PCAxis.Web.Controls.CommandBar.CommandBarCodebehind.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by StefanDK** [comment]
@statgreen, @MikaelNordberg and @petroslikidis 

I got this exception too. I fixed it by editing the method HidePluginDropDown() in the following file: in the PxWeb project: 

**PxWeb/PCAxis.Web.Controls/CommandBar/CommandBarCodebehind.vb**

Even though the exception occured PxWeb did perform the TimeSplit action flawless - it was only the GUI that failed afterwards.

```
Private Sub HidePluginDropDown(ByVal dropdown As DropDownList, ByVal pluginId As String)
    If dropdown Is Nothing Then
        Return
    Else
        // Original code ...
    End If
End Sub
```

The only thing the change does is checking if the dropdownlist is null, I don't know why it is null, and it has been hard for me to debug the problem since there are some thread handling going on that I cannot properly navigate, it seems.

So even if this fix does solve the problem (and it does), it might introduce unexpected behaviour in other parts of the code, but I think there is little risk of this occuring. 

I can open a pull/push request, but I am quite new with Git and it has been a long time since I done it - and the change is really small so I have attached the file and hope you can merge it in.

**Comment by Hansseman** [comment]
The time split error still exists in PxWeb 2022v1!
https://pxwebdemo.scb.se/pxweb/en/Example/Example__Month/PR0101B3.px
Get a timeseries and select "edit and calculate" and "split timeseries" and you will get an error, but if you do a reload at that point it seams to work.

Earlier i tried the same thing with a "saved query" and it failed. Have not tried it with version 2022v1
It does not give me the latest updated figures.

This  is a valuable tool witch makes it possible to compare for example months of different years of the time series in a table. The only reason we still have to make tables with the split time variables (ex. Years and months) is this bug in PxWeb. 
It is hard to tell people to make the tables in PxWeb the right way when this critical feature is not working right.

**Comment by jerikso** [comment]
The fix mentioned by @StefanDK is implemented in #472
